name: Log
on:
   workflow_dispatch: 
concurrency:
   group: publish
   cancel-in-progress: false
jobs:
   log:
      runs-on: ubuntu-latest
      permissions:
         contents: read
      steps:
         - uses: actions/checkout@v4
         - name: Setup Bun
           uses: oven-sh/setup-bun@v1
           with:
              bun-version: latest
         - name: Install dependencies
           shell: bash
           run: bun install
         - name: Log to val town
           run: bun run scripts/log.ts
           env:
              STAGE: prod
              ALCHEMY_PASSWORD: ${{ secrets.ALCHEMY_PASSWORD }}
